# Generated by Django 3.2.4 on 2021-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500)),
                ('item_id', models.IntegerField()),
                ('notification_date', models.DateTimeField()),
                ('is_visited', models.BooleanField()),
            ],
        ),
    ]
