# Generated by Django 3.2.4 on 2021-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_date',
            field=models.DateField(),
        ),
    ]
