# Generated by Django 3.2.6 on 2021-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_notifications_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.IntegerField(default=1),
        ),
    ]
