# Generated by Django 3.2.4 on 2021-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('last_order_date', models.DateField()),
                ('expected_order_date', models.DateField()),
            ],
        ),
    ]
