# Generated by Django 3.2.4 on 2021-06-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinventory',
            name='item',
        ),
    ]
