# Generated by Django 3.2.4 on 2021-06-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_foodinventory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_types',
            fields=[
                ('type', models.CharField(max_length=50)),
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='foodinventory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.product_types'),
        ),
    ]
