# Generated by Django 3.2.4 on 2021-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_delete_product_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('type_id', models.IntegerField()),
            ],
        ),
    ]
