# Generated by Django 3.2.4 on 2021-06-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_item_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_types',
            name='id',
        ),
        migrations.AlterField(
            model_name='item_types',
            name='type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
