# Generated by Django 3.2.4 on 2021-06-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20210617_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinventory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.item_types'),
        ),
    ]
