# Generated by Django 3.2.4 on 2021-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_foodinventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinventory',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
