# Generated by Django 3.2.4 on 2021-06-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_foodinventory_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.item_types')),
            ],
        ),
    ]
