# Generated by Django 3.2.4 on 2021-06-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.product_type'),
        ),
        migrations.AlterField(
            model_name='foodinventory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.item_types'),
        ),
    ]
