# Generated by Django 3.2.4 on 2021-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_auto_20210623_1605'),
        ('operations', '0013_auto_20210622_1358'),
    ]

    operations = [
    ]
