# Generated by Django 3.2.4 on 2021-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20210630_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('Set', 'Set'), ('Number', 'Number')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('paid_by', models.CharField(choices=[('Shreya', 'Shreya'), ('Pankaj', 'Pankaj'), ('Company', 'Company'), ('Others', 'Others')], max_length=50)),
                ('purchase_date', models.DateField()),
                ('additional_info', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
