# Generated by Django 3.2.4 on 2021-07-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20210630_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_shirt_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('receiving_date', models.DateField()),
                ('size', models.CharField(choices=[('XS', 'Extra-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large'), ('XXL', 'XXL')], max_length=50)),
                ('previous_stock', models.PositiveIntegerField()),
                ('ordered_quantity', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField()),
                ('allotted', models.PositiveIntegerField(default=0)),
                ('remaining', models.PositiveIntegerField()),
                ('paid_by', models.CharField(max_length=50)),
                ('additional', models.CharField(max_length=500)),
            ],
        ),
    ]
