# Generated by Django 3.2.4 on 2021-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20210630_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyWeeklyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Foods'), ('2', 'Beverage')], default='1', max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('gram', 'gm'), ('kilogram', 'kg'), ('centimeter', 'cm'), ('dozen', 'dz'), ('liter', 'l'), ('mililiters', 'ml')], default='None', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(null=True)),
                ('purchase_date', models.DateField()),
                ('aditional_info', models.CharField(max_length=200)),
            ],
        ),
    ]
