# Generated by Django 3.2.4 on 2021-07-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_dailyweeklyitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyweeklyitems',
            name='price',
        ),
        migrations.AlterField(
            model_name='dailyweeklyitems',
            name='aditional_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyweeklyitems',
            name='type',
            field=models.CharField(choices=[('1', 'Foods'), ('2', 'Beverage'), ('3', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyweeklyitems',
            name='unit',
            field=models.CharField(choices=[('gm', 'gram'), ('kg', 'kilogram'), ('number', 'number'), ('dozen', 'dozen'), ('liter', 'liter'), ('ml', 'mililiter')], max_length=50),
        ),
    ]
