# Generated by Django 3.2.4 on 2021-08-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_adhocitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocitems',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
