# Generated by Django 3.2.4 on 2021-08-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_adhocitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocitems',
            name='unit',
        ),
    ]
