# Generated by Django 3.2.4 on 2021-07-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20210723_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendorContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=100)),
                ('contact_no', models.PositiveIntegerField()),
                ('alternate_contact_no', models.PositiveIntegerField()),
                ('nominal_charges', models.PositiveIntegerField()),
                ('aditional_info', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyweeklyitems',
            name='unit',
            field=models.CharField(choices=[('Gm', 'gram'), ('Kg', 'kilogram'), ('No.s', 'number'), ('Dozen', 'dozen'), ('Liter', 'liter'), ('Ml', 'mililiter')], max_length=50),
        ),
        migrations.CreateModel(
            name='repairServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(max_length=50)),
                ('charges', models.PositiveIntegerField()),
                ('vendor_name', models.CharField(max_length=50)),
                ('contact_no', models.PositiveIntegerField()),
                ('paid_by', models.CharField(choices=[('shreya', 'Shreya'), ('pankaj', 'Pankaj'), ('company', 'Company'), ('others', 'Others')], max_length=50)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('digital', 'Digital'), ('company account', 'Company Account'), ('others', 'Others')], max_length=50)),
                ('next_service_date', models.DateField()),
                ('aditional_info', models.CharField(blank=True, max_length=200)),
                ('service_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vendorcontactlist')),
            ],
        ),
    ]
