# Generated by Django 3.2.4 on 2021-07-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_t_shirt_inventory_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_shirt_inventory',
            name='additional',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
