# Generated by Django 3.2.4 on 2021-07-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_adhocitems'),
        ('operations', '0018_alter_t_shirt_inventory_additional'),
    ]

    operations = [
    ]
