# Generated by Django 3.2.4 on 2021-07-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_rename_alternate_contact_no_vendorcontactlist_alternate_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcontactlist',
            old_name='services',
            new_name='service',
        ),
    ]
