# Generated by Django 3.2.4 on 2021-07-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_merge_20210727_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_shirt_inventory',
            options={'ordering': ['-receiving_date']},
        ),
    ]
