# Generated by Django 3.2.4 on 2021-07-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_rename_services_vendorcontactlist_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairservices',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='alternate_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
    ]
