# Generated by Django 3.2.4 on 2021-07-30 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20210728_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairservices',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='alternate_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '8743457650'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '8743457650'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
