# Generated by Django 3.2.4 on 2021-08-05 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_auto_20210730_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='alternate_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be positive intergers.Up to 10 digits allowed.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be positive intergers.Up to 10 digits allowed.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='nominal_charges',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
