# Generated by Django 3.2.6 on 2021-08-05 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0022_historicalrecurringitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalt_shirt_inventory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('receiving_date', models.DateField()),
                ('size', models.CharField(choices=[('XS', 'Extra-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large'), ('XXL', 'XXL')], max_length=50)),
                ('previous_stock', models.PositiveIntegerField()),
                ('ordered_quantity', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField()),
                ('allotted', models.PositiveIntegerField(default=0)),
                ('remaining', models.PositiveIntegerField()),
                ('paid_by', models.CharField(max_length=50)),
                ('additional', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical t_shirt_inventory',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
