# Generated by Django 3.2.6 on 2021-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_historicalt_shirt_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalt_shirt_inventory',
            name='user',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='t_shirt_inventory',
            name='user',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
