# Generated by Django 3.2.4 on 2021-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_alter_repairservices_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairservices',
            name='paid_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='repairservices',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
    ]
