# Generated by Django 3.2.4 on 2021-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_auto_20210813_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringitems',
            name='paid_by',
            field=models.CharField(choices=[('shreya', 'Shreya'), ('pankaj', 'Pankaj'), ('company', 'Company'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repairservices',
            name='paid_by',
            field=models.CharField(choices=[('shreya', 'Shreya'), ('pankaj', 'Pankaj'), ('company', 'Company'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repairservices',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('digital', 'Digital'), ('company_account', 'Company_Account'), ('others', 'Others')], max_length=50),
        ),
    ]
