# Generated by Django 3.2.4 on 2021-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_auto_20210813_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='nominal_charges',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
