# Generated by Django 3.2.4 on 2021-08-19 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_alter_vendorcontactlist_nominal_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='aditional_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontactlist',
            name='alternate_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be positive intergers.Up to 10 digits allowed.', regex='^\\d{10}$')]),
        ),
    ]
