# Generated by Django 3.2.6 on 2022-02-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_alter_adhocitems_paid_by'),
        ('operations', '0024_auto_20210812_1246'),
        ('operations', '0029_auto_20210819_1213'),
    ]

    operations = [
    ]
